 - name: test
   become: true
   hosts: all
   remote_user: timur
   tasks:
    - name: Add Docker repo
      deb822_repository:
       name: docker
       types: deb
       uris: https://download.docker.com/linux/ubuntu
       suites: resolute
       components: stable
       architectures: amd64
       signed_by: https://download.docker.com/linux/ubuntu/gpg
      notify: apt_cache_update
    - name: Install Docker 
      apt:
       name: 
        - docker-ce
        - docker-compose-plugin
       state: present
    
    - name: Copy files
      ansible.builtin.copy:
       src: ../files
       dest: /compose

    - name: Start Compose
      community.docker.docker_compose_v2:
       project_src: /compose/files
       state: present